blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://github.com/unbgio/browser-sdk/security/advisories/new
    about: Please report security vulnerabilities privately via GitHub Security Advisories.
